name: Build and Test

on:
  push:
    branches:
      - master  # or your main branch
  pull_request:
    branches:
      - master  # or your main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake \
            build-essential \
            libssl-dev \
            libcurl4-openssl-dev \
            libmysqlclient-dev \
            default-libmysqlclient-dev \
            libpq-dev \
            libsodium-dev \
            libgnutls28-dev \
            zlib1g-dev \
            git \
            libapr1-dev \
            libaprutil1-dev \
            libodbcinstq4-dev \
            apache2-dev

      - name: Create build directory
        run: mkdir build

      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build the project
        run: cmake --build build --config Release

      - name: Run tests
        run: cd build && ctest
      working-directory: ${{github.workspace}}/build
      shell: bash
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C $BUILD_TYPE
