name: Build and Test

on:
  push:
    branches:
      - master  # or your main branch
  pull_request:
    branches:
      - master  # or your main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update || { echo "apt-get update failed"; exit 1; }
          sudo apt-get install -y --no-install-recommends \
            cmake \
            build-essential \
            libssl-dev \
            libcurl4-openssl-dev \
            libmysqlclient-dev \
            default-libmysqlclient-dev \
            libpq-dev \
            libsodium-dev \
            libgnutls28-dev \
            zlib1g-dev \
            git \
            libapr1-dev \
            libaprutil1-dev \
            libodbcinstq4-dev \
            apache2-dev || { echo "apt-get install failed"; exit 1; }

      - name: Create build directory
        run: mkdir build

      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build the project
        run: cmake --build build --config Release

      - name: Run tests
        run: cd build && ctest
